
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvhgfxeqrjavxlzvxqqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2aGdmeGVxcmphdnhsenZ4cXFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNjMxMzcsImV4cCI6MjA2MDgzOTEzN30.6wPnRGIiUKDymhZ-vWE2ikG6DT4mEAzbMUKV9iFQ1r4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Define our own type for the database structure
// This acts as a workaround since we can't modify the types.ts file
export type CustomDatabase = {
  public: {
    Tables: {
      missions: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          type: string | null;
          points: number;
          is_active: boolean;
          advertiser_id: string;
          requirements: any[] | null;
          start_date: string | null;
          end_date: string | null;
          target_audience_gender: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          type?: string | null;
          points?: number;
          is_active?: boolean;
          advertiser_id: string;
          requirements?: any[] | null;
          start_date?: string | null;
          end_date?: string | null;
          target_audience_gender?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string | null;
          type?: string | null;
          points?: number;
          is_active?: boolean;
          advertiser_id?: string;
          requirements?: any[] | null;
          start_date?: string | null;
          end_date?: string | null;
          target_audience_gender?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      submissions: {
        Row: {
          id: string;
          mission_id: string;
          user_id: string;
          status: string;
          content: any | null;
          points_awarded: number | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          mission_id: string;
          user_id: string;
          status?: string;
          content?: any | null;
          points_awarded?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          mission_id?: string;
          user_id?: string;
          status?: string;
          content?: any | null;
          points_awarded?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
};

// Create and export the typed Supabase client
export const supabase = createClient<CustomDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
